services:
  server:
    container_name: ${APP_HOST}
    build: ./server
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    networks:
      - erraton_network

  client:
    container_name: ${CLIENT_HOST}
    build: ./client
    restart: unless-stopped
    ports:
      - ${CLIENT_PORT}:5173
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    networks:
      - erraton_network
    command: ["npm", "run", "dev", "--", "--host"]

  mongo:
    image: mongo
    command: ["mongod", "--quiet"]
    container_name: ${DB_HOST}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:27017
    networks:
      - erraton_network

volumes:
  server_node_modules:
  client_node_modules:

networks:
  erraton_network:
