services:

  app:
    container_name: ${APP_HOST}
    build: .
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - erraton_network
  mongo:
    image: mongo
    container_name: ${DB_HOST}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:27017
    networks:
      - erraton_network
  
volumes:
  node_modules:
networks:
  erraton_network:
    